# language (日志啥的语言类型)
language: zh
# task type(ner,cls,generate)
type: GEN
model: GPT
struct: GPT-ConditionalGeneration-QA
# required params (常规必备参数)
base: 
  task_name: gen_QA_GPT_V3
  data_dir: /data1/anon/Anon-NLP-Toolkit/datasets/gen_QA/medical_QA_simplify_test
  model_name_or_path: /data1/PRETRAIN_MODEL/gpt2-chinese-cluecorpussmall
  output_dir: /data/anon/output_dir
  cache_dir: /data/anon/cache_dir
  # 是否输出数据例子
  print_data_examples: false
  # 在QA中作为答案最大长度
  train_max_seq_len: 512
  eval_max_seq_len: 512
  # 在QA中作为问题最大长度
  train_max_utterance_len: 256
  eval_max_utterance_len: 256
  do_train: true
  do_eval: false
  do_predict: false
  # 是否需要对初始状态的模型进行评估
  need_init_model_evaluate: false
  evaluate_during_training: true
  do_lower_case: true
  per_gpu_train_batch_size: 16
  per_gpu_eval_batch_size: 12
  gradient_accumulation_steps: 1
  learning_rate: 0.0001
  weight_decay: 0.01
  adam_epsilon: 0.00000001
  max_grad_norm: 1.0
  num_train_epochs: 1
  max_steps: -1
  warmup_proportion: 0.1
  logging_steps: -1
  save_steps: 50
  eval_all_checkpoints: false
  predict_checkpoints: 40
  no_cuda: false
  overwrite_output_dir: true
  # 是否需要继续训练（设置true时 overwrite_output_dir不生效）
  continue_train: true
  overwrite_cache: false
  seed: 42
  fp16: false
  fp16_opt_level: O1
  local_rank: -1
  server_ip:
  server_port:
# 过大数据集分片训练设置
big_data:
  # 训练数据集是否需要分片
  need_split_shard: true
  # 训练数据集的分片大小
  shard_size: 100000
  # 分片前是否需要shuffle
  shuffle_before_split: true
  # 大数据的总步数(需要自己计算)
  big_data_total_step: 331301

  start_shard_idx: 0


n_gpu_balance:
  first_gpu_batch_size : 1


# (adversarial training params) 对抗训练参数
adversarial:
  do_adv: true
  adv_epsilon: 1.0
  adv_name: word_embeddings


gen_special:
  # 是否要在保存每一个ckpt之前进行text评估（bleu,rouge,distinct,gleu）
  text_eval_before_save: true
  # 如果存在多个问题，该如何选择 0-用最长的，1-都用
  muti_question_strategy: 0




  



  




  
