# language (日志啥的语言类型)
language: zh
# task type(ner,cls,generate)
type: NER
model: bert
struct: bertSpan
# required params (常规必备参数)
base: 
  task_name: ner_test_bs
  data_dir: /data1/anon/Anon-NLP-Toolkit/datasets/cner
  model_name_or_path: /data1/PRETRAIN_MODEL/bert-base-chinese
  output_dir: /data1/anon/BERT-NER-Pytorch/outputs/cner
  cache_dir: /data1/anon/BERT-NER-Pytorch/outputs/cache
  train_max_seq_len: 64
  eval_max_seq_len: 64
  do_train: true
  do_eval: true
  do_predict: true
  evaluate_during_training: true
  do_lower_case: true
  per_gpu_train_batch_size: 128
  per_gpu_eval_batch_size: 128
  gradient_accumulation_steps: 1
  learning_rate: 0.00005
  weight_decay: 0.01
  adam_epsilon: 0.00000001
  max_grad_norm: 1.0
  num_train_epochs: 3
  max_steps: -1
  warmup_proportion: 0.1
  logging_steps: 10
  save_steps: 20
  eval_all_checkpoints: true
  predict_checkpoints: 40
  no_cuda: false
  overwrite_output_dir: true
  overwrite_cache: false
  seed: 42
  fp16: false
  fp16_opt_level: O1
  local_rank: -1
  server_ip:
  server_port:

# (adversarial training params) 对抗训练参数
adversarial:
  do_adv: true
  adv_epsilon: 1.0
  adv_name: word_embeddings

# ner training (ner 独有参数)
ner_special:
  markup: bios
  loss_type: ce
  crf:
    crf_learning_rate: 0.00005
  



  




  
