# language (日志啥的语言类型)
language: zh
# task type(ner,cls,generate)
type: CLS
model: bert
struct: bertSoftmax
# required params (常规必备参数)
base: 
  task_name: cls_test_bs_augeda
  data_dir: /data1/anon/Anon-NLP-Toolkit/datasets/waimai_csv
  model_name_or_path: /data1/PRETRAIN_MODEL/bert-base-chinese
  output_dir: /data1/anon/BERT-NER-Pytorch/outputs/cls_waimai_c
  cache_dir: /data1/anon/BERT-NER-Pytorch/outputs/cache
  train_max_seq_len: 128
  eval_max_seq_len: 128
  do_train: true
  do_eval: true
  do_predict: false
  evaluate_during_training: true
  do_lower_case: true
  per_gpu_train_batch_size: 64
  per_gpu_eval_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 0.00005
  weight_decay: 0.01
  adam_epsilon: 0.00000001
  max_grad_norm: 1.0
  num_train_epochs: 1
  max_steps: -1
  warmup_proportion: 0.1
  logging_steps: 40
  save_steps: 40
  eval_all_checkpoints: true
  predict_checkpoints: 40
  no_cuda: false
  overwrite_output_dir: true
  overwrite_cache: false
  seed: 42
  fp16: false
  fp16_opt_level: O1
  local_rank: -1
  server_ip:
  server_port:

# (adversarial training params) 对抗训练参数
adversarial:
  do_adv: true
  adv_epsilon: 1.0
  adv_name: word_embeddings


data_augments:
  do_aug: true
  # (DM,EDA,Back_Translation,Over_Sample) 未完成
  aug_function: EDA
  #  (MAX,MEAN,or a int type number)
  # MAX : 所有标签数据条数都照最大数据条目类别靠齐
  # MEAN : 所有标签下数据条目对准各各标签条目数的平均，多余数据将会随机删除
  # int: 传入int类型的数据，则所有标签下数据条数都调整为该数值，多余数据将会随机删除
  aug_baseline:  MAX

# cls training (cls 独有参数)
cls_special:
  loss_type: ce
  



  




  
